; allow_url_fopen = Off
display_errors = Off
display_startup_errors = Off
doc_root = /var/www/html
enable_dl = Off
file_uploads = Off
html_errors = Off
log_errors = On
max_execution_time = 0
max_input_nesting_level = 10
max_input_vars = 100
memory_limit = 64M
post_max_size = 1M
short_open_tag = Off
sys_temp_dir = /tmp
upload_tmp_dir = /dev/null
date.timezone = Europe/Paris
