version: "3"

# docker build -t griotte:v2.3.1 .
# docker service rm griotte_graphs griotte_incoming griotte_proxy
# docker stack deploy -c docker-compose.yml --prune --detach=false griotte

services:

  proxy:
    image: nginx:1.31-alpine@sha256:8b1e78743a03dbb2c95171cc58639fef29abc8816598e27fb910ed2e621e589a
    ports:
      - "8081:8081"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,volume-nocopy
      - ./nginx/site-incoming.conf:/etc/nginx/conf.d/site-incoming.conf:ro,volume-nocopy
      - ./nginx/site-graphs.conf:/etc/nginx/conf.d/site-graphs.conf:ro,volume-nocopy
      - ./www/statics:/var/www/html/statics:ro,volume-nocopy
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      resources:
        limits:
          cpus: '0.25'
          memory: 50M

  incoming:
    image: "griotte:v2.3.1"
    tmpfs:
      - /tmp
      - /var/www/run
    volumes:
      - ./app/config.griot.ini:/var/www/app/config.ini:ro,volume-nocopy
      - ./volumes/db:/var/www/db
    environment:
      GRIOTTE_LABEL: Griotte
      GRIOTTE_ROOT_PATH: /var/www
      GRIOTTE_DB_PATH: /var/www/db
      GRIOTTE_RUN_PATH: /var/www/run
      GRIOTTE_BUFFER_DELAY: 300
      GRIOTTE_NODE_DELAY: 60
      GRIOTTE_DEBUG: "false"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.25'
          memory: 100M

  graphs:
    image: "griotte:v2.3.1"
    tmpfs:
      - /tmp
    volumes:
      - ./app/config.griot.ini:/var/www/app/config.ini:ro,volume-nocopy
      - ./volumes/db:/var/www/db:ro,volume-nocopy
    environment:
      GRIOTTE_LABEL: Griotte
      GRIOTTE_ROOT_PATH: /var/www
      GRIOTTE_DB_PATH: /var/www/db
      GRIOTTE_DEBUG: "false"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
