version: "3"

# docker build -t griotte:2026-05-08_15-40 .
# docker build -t "$(yq -r .services.api.image docker-compose.yml)" .
# docker build -t "$(yq -r .services.graphs.image docker-compose.yml)" .
# docker stack deploy -c docker-compose.yml --prune griotte

services:

  api:
    image: "griotte:2026-05-08_15-40"
    tmpfs:
      - /tmp
      - /var/www/run
    ports:
      - "8081:80"
    volumes:
      - '/home/pi/griotte/app/config.griot.ini:/var/www/app/config.ini'
      - '/home/pi/griotte/volumes/db:/var/www/db'
    environment:
      GRIOTTE_LABEL: Griotte
      GRIOTTE_ROOT_PATH: /var/www
      GRIOTTE_DB_PATH: /var/www/db
      GRIOTTE_RUN_PATH: /var/www/run
      GRIOTTE_BUFFER_DELAY: 300
      GRIOTTE_NODE_DELAY: 60

  graphs:
    image: "griotte:2026-05-08_15-40"
    tmpfs:
      - /tmp
    ports:
      - "80:80"
    volumes:
      - '/home/pi/griotte/app/config.griot.ini:/var/www/app/config.ini'
      - '/home/pi/griotte/volumes/db:/var/www/db:ro,volume-nocopy'
    environment:
      GRIOTTE_LABEL: Griotte
      GRIOTTE_ROOT_PATH: /var/www
      GRIOTTE_DB_PATH: /var/www/db
