map $request_method $griotte_target {
  default  127.0.0.1:80;
  "HEAD"   griotte_graphs:9000;
  "GET"    griotte_graphs:9000;
  "POST"   griotte_incoming:9000;
}

map $uri $fpm_backend {
  default 127.0.0.1:80;
  /graphs.status     griotte_graphs:9000;
  /graphs.ping       griotte_graphs:9000;
  /incoming.status   griotte_incoming:9000;
  /incoming.ping     griotte_incoming:9000;
}

map $uri $fpm_uri {
  default 127.0.0.1:80;
  /graphs.status     /fpm-status;
  /graphs.ping       /ping;
  /incoming.status   /fpm-status;
  /incoming.ping     /ping;
}


log_format griot '$remote_addr s=$status b=$body_bytes_sent uct=$upstream_connect_time uht=$upstream_header_time urt=$upstream_response_time rt=$request_time "$http_user_agent" "$request"';

server {
  listen  80;
  server_name _;
  root  /var/www/html;
  index  index.php index.html;

  error_log /var/log/nginx/error.log info;
  access_log /var/log/nginx/access.log griot;

  error_page  500 502 503 504  /50x.html;
  keepalive_timeout 0;

  location = /50x.html {
    root  /usr/share/nginx/html;
  }

  location = /favicon.ico {
    return  404;
  }

  location ~ ^/(graphs|incoming).(ping|status)$ {
    limit_except GET {
      allow  all;
    }

    resolver       127.0.0.11 valid=10s;
    include        fastcgi_params;
    fastcgi_pass   $fpm_backend;
    fastcgi_param  SCRIPT_FILENAME $fpm_uri;
    fastcgi_param  SCRIPT_NAME $fpm_uri;
  }

  location ~ \.php$ {
    internal;
    resolver       127.0.0.11 valid=10s;
    include        fastcgi_params;
    fastcgi_pass   $griotte_target;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  /var/www/html$fastcgi_script_name;
    fastcgi_hide_header X-Powered-By;
  }

  location / {
    limit_except GET POST {
      allow  all;
    }
    try_files  $uri /index.php?$query_string;
  }

}
