server {
  listen  80;
  server_name _;
  root  /var/www/html;
  index  index.php index.html;

  error_page  500 502 503 504  /50x.html;

  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-XSS-Protection "1; mode=block" always;

  location = /50x.html {
    root  /usr/share/nginx/html;
  }

  location / {
    try_files      $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    resolver       127.0.0.11 valid=10s;
    set            $target griotte_incoming:9000;
    include        fastcgi_params;
    fastcgi_pass   $target;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  /var/www/html$fastcgi_script_name;
  }

}
